### ISSUE TITLE
Installation on CentOS

### ISSUE THREAD

**Issue by Pradyumna94** [durka/vlc-matlab#4]
Hi,

In order to install vlc-matlab on CentOS, how do I install VLC with development headers in CentOS 7?

**Comment by durka** [comment]
Unfortunately I don't use CentOS myself, and I asked someone who does but they couldn't find a VLC package. You may be able to enable the RPMFusion or RPMForge repositories and then follow the instructions here: http://www.videolan.org/vlc/#download

Otherwise I recommend installing VLC from source.
